<html>
<head>
<title>TestNG:  UnitTests</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>UnitTests</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>8/1/0</td>
</tr><tr>
<td>Started on:</td><td>Fri Feb 05 09:11:49 EST 2010</td>
</tr>
<tr><td>Total time:</td><td>0 seconds (508 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td><b>Instance</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td width="30%"><b>Exception</b></td>
</tr>
<tr>
<td title='com.pillartech.blog.AccountTest.shouldStoreEncryptedPassword()'><b>shouldStoreEncryptedPassword</b><br>Test class:UnitTests</td>
<td>com.pillartech.blog.AccountTest@2ec791b9</td><td>0</td>
<td><div><pre>org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Misplaced argument matcher detected here:
-&gt; at com.pillartech.blog.AccountTest.shouldStoreEncryptedPassword(AccountTest.java:19)

You cannot use argument matchers outside of verification or stubbing.
Examples of correct usage of argument matchers:
    when(mock.get(anyInt())).thenReturn(null);
    doThrow(new RuntimeException()).when(mock).someVoidMethod(anyObject());
    verify(mock).someMethod(contains("foo"))

Also, this error might show up because you use argument matchers with methods that cannot be mocked.
Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode() methods.

	at com.pillartech.blog.AccountTest.shouldStoreEncryptedPassword(AccountTest.java:19)
... Removed 22 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace831013236", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace831013236'><pre>org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Misplaced argument matcher detected here:
-&gt; at com.pillartech.blog.AccountTest.shouldStoreEncryptedPassword(AccountTest.java:19)

You cannot use argument matchers outside of verification or stubbing.
Examples of correct usage of argument matchers:
    when(mock.get(anyInt())).thenReturn(null);
    doThrow(new RuntimeException()).when(mock).someVoidMethod(anyObject());
    verify(mock).someMethod(contains("foo"))

Also, this error might show up because you use argument matchers with methods that cannot be mocked.
Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode() methods.

	at com.pillartech.blog.AccountTest.shouldStoreEncryptedPassword(AccountTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:644)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:546)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:700)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1002)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:137)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.runWorkers(TestRunner.java:908)
	at org.testng.TestRunner.privateRun(TestRunner.java:617)
	at org.testng.TestRunner.run(TestRunner.java:498)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:329)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:324)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:201)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:915)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:879)
	at org.testng.TestNG.run(TestNG.java:787)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:127)
</pre></div></td>
</tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td><b>Instance</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td width="30%"><b>Exception</b></td>
</tr>
<tr>
<td title='com.pillartech.blog.LoginServiceTest.shouldInactivateAfterThreeFailedPasswords()'><b>shouldInactivateAfterThreeFailedPasswords</b><br>Test class:UnitTests</td>
<td>com.pillartech.blog.LoginServiceTest@303020ad</td><td>0</td>
<td></td>
</tr>
<tr>
<td title='com.pillartech.blog.LoginServiceTest.shouldLoginValidPasswords()'><b>shouldLoginValidPasswords</b><br>Test class:UnitTests</td>
<td>com.pillartech.blog.LoginServiceTest@303020ad</td><td>0</td>
<td></td>
</tr>
<tr>
<td title='com.pillartech.blog.LoginServiceTest.shouldNotInactivateUsersAfterThreeTotalFailedPasswords_CustomMatcherApproach()'><b>shouldNotInactivateUsersAfterThreeTotalFailedPasswords_CustomMatcherApproach</b><br>Test class:UnitTests</td>
<td>com.pillartech.blog.LoginServiceTest@303020ad</td><td>0</td>
<td></td>
</tr>
<tr>
<td title='com.pillartech.blog.LoginServiceTest.shouldNotInactivateUsersAfterThreeTotalFailedPasswords_RepetitiveApproach()'><b>shouldNotInactivateUsersAfterThreeTotalFailedPasswords_RepetitiveApproach</b><br>Test class:UnitTests</td>
<td>com.pillartech.blog.LoginServiceTest@303020ad</td><td>0</td>
<td></td>
</tr>
<tr>
<td title='com.pillartech.blog.LoginServiceTest.shouldNotLoginBadPasswords()'><b>shouldNotLoginBadPasswords</b><br>Test class:UnitTests</td>
<td>com.pillartech.blog.LoginServiceTest@303020ad</td><td>0</td>
<td></td>
</tr>
<tr>
<td title='com.pillartech.blog.LoginServiceTest.shouldThrowAnExceptionIfAccountIsInactive()'><b>shouldThrowAnExceptionIfAccountIsInactive</b><br>Test class:UnitTests</td>
<td>com.pillartech.blog.LoginServiceTest@303020ad</td><td>0</td>
<td><div><pre>com.pillartech.blog.exception.AccountRevokedException: Account has been revoked for too many failed login attempts.
	at com.pillartech.blog.LoginServiceImpl.login(LoginServiceImpl.java:25)
	at com.pillartech.blog.LoginServiceTest.shouldThrowAnExceptionIfAccountIsInactive(LoginServiceTest.java:140)
... Removed 22 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace809606405", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace809606405'><pre>com.pillartech.blog.exception.AccountRevokedException: Account has been revoked for too many failed login attempts.
	at com.pillartech.blog.LoginServiceImpl.login(LoginServiceImpl.java:25)
	at com.pillartech.blog.LoginServiceTest.shouldThrowAnExceptionIfAccountIsInactive(LoginServiceTest.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:644)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:546)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:700)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1002)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:137)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.runWorkers(TestRunner.java:908)
	at org.testng.TestRunner.privateRun(TestRunner.java:617)
	at org.testng.TestRunner.run(TestRunner.java:498)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:329)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:324)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:201)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:915)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:879)
	at org.testng.TestNG.run(TestNG.java:787)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:127)
</pre></div></td>
</tr>
<tr>
<td title='com.pillartech.blog.LoginServiceTest.shouldThrowAnExceptionIfAccountIsNotFound()'><b>shouldThrowAnExceptionIfAccountIsNotFound</b><br>Test class:UnitTests</td>
<td>com.pillartech.blog.LoginServiceTest@303020ad</td><td>0</td>
<td><div><pre>com.pillartech.blog.exception.AccountNotFoundException: Unable to find account due to underlying issue
	at com.pillartech.blog.LoginServiceImpl.findAccountByUsername(LoginServiceImpl.java:48)
	at com.pillartech.blog.LoginServiceImpl.login(LoginServiceImpl.java:22)
	at com.pillartech.blog.LoginServiceTest.shouldThrowAnExceptionIfAccountIsNotFound(LoginServiceTest.java:131)
Caused by: com.pillartech.blog.exception.AccountNotFoundException: Account with username todd was not found.
	at com.pillartech.blog.LoginServiceImpl.findAccountByUsername(LoginServiceImpl.java:43)
	... 24 more
... Removed 22 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1675553600", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1675553600'><pre>com.pillartech.blog.exception.AccountNotFoundException: Unable to find account due to underlying issue
	at com.pillartech.blog.LoginServiceImpl.findAccountByUsername(LoginServiceImpl.java:48)
	at com.pillartech.blog.LoginServiceImpl.login(LoginServiceImpl.java:22)
	at com.pillartech.blog.LoginServiceTest.shouldThrowAnExceptionIfAccountIsNotFound(LoginServiceTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:644)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:546)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:700)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1002)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:137)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.runWorkers(TestRunner.java:908)
	at org.testng.TestRunner.privateRun(TestRunner.java:617)
	at org.testng.TestRunner.run(TestRunner.java:498)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:329)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:324)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:201)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:915)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:879)
	at org.testng.TestNG.run(TestNG.java:787)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:127)
Caused by: com.pillartech.blog.exception.AccountNotFoundException: Account with username todd was not found.
	at com.pillartech.blog.LoginServiceImpl.findAccountByUsername(LoginServiceImpl.java:43)
	... 24 more
</pre></div></td>
</tr>
<tr>
<td title='com.pillartech.blog.LoginServiceTest.shouldThrowBusinessExceptionIfDatabaseIsDown()'><b>shouldThrowBusinessExceptionIfDatabaseIsDown</b><br>Test class:UnitTests</td>
<td>com.pillartech.blog.LoginServiceTest@303020ad</td><td>0</td>
<td><div><pre>com.pillartech.blog.exception.AccountNotFoundException: Unable to find account due to underlying issue
	at com.pillartech.blog.LoginServiceImpl.findAccountByUsername(LoginServiceImpl.java:48)
	at com.pillartech.blog.LoginServiceImpl.login(LoginServiceImpl.java:22)
	at com.pillartech.blog.LoginServiceTest.shouldThrowBusinessExceptionIfDatabaseIsDown(LoginServiceTest.java:146)
Caused by: java.sql.SQLException
	at com.pillartech.blog.LoginServiceImpl.findAccountByUsername(LoginServiceImpl.java:41)
	... 24 more
... Removed 22 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1943692956", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1943692956'><pre>com.pillartech.blog.exception.AccountNotFoundException: Unable to find account due to underlying issue
	at com.pillartech.blog.LoginServiceImpl.findAccountByUsername(LoginServiceImpl.java:48)
	at com.pillartech.blog.LoginServiceImpl.login(LoginServiceImpl.java:22)
	at com.pillartech.blog.LoginServiceTest.shouldThrowBusinessExceptionIfDatabaseIsDown(LoginServiceTest.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:644)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:546)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:700)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1002)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:137)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.runWorkers(TestRunner.java:908)
	at org.testng.TestRunner.privateRun(TestRunner.java:617)
	at org.testng.TestRunner.run(TestRunner.java:498)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:329)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:324)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:201)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:915)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:879)
	at org.testng.TestNG.run(TestNG.java:787)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:127)
Caused by: java.sql.SQLException
	at com.pillartech.blog.LoginServiceImpl.findAccountByUsername(LoginServiceImpl.java:41)
	... 24 more
</pre></div></td>
</tr>
</table><p>
</body>
</html>